### PR TITLE
Admin View

### PR DESCRIPTION
**Pull request by dwthomas77**
If you go to "/", it will automatically redirect you to "/products" or "/admin" depending on your role. We will later add the appropriate nav links to show/hide accordingly. 

If you don't have access to "/admin" and you go to that route directly, it will not redirect you, but will show you a "cannot display route" message.

### CODE REVIEW

**Comment by dwthomas77** [comment]
I having trouble manually changing the role value from the firebase console, I think it might be a database rule thing.  If you can figure out how to manually change a user's role we should set this back to CUSTOMER.

**Comment by evandana** [comment]
I was able to update it in the FB DB to be either CUSTOMER or SELLER. Do you want to update the PR or should I?

**Comment by evandana** [comment]
I've updated the PR and added a bit of routing behavior. If you go to "/", it will automatically redirect you to "/products" or "/admin" depending on your role. We will later add the appropriate nav links to show/hide accordingly.

**Comment by evandana** [comment]
Will do

**Pull request merged**
